print stuff

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -30,68 +30,72 @@ jobs:
     steps:
       - name: Check out repository code
         uses: actions/checkout@v4
-      - id: store_previous_version
+      - name: Print stuff
         run: |
-          previousVersion=$(ruby -r "./version.rb" -e "print_version")
-          echo "previousVersion=$previousVersion" >> "$GITHUB_OUTPUT"
-      - name: Update the version.json file
-        if: inputs.version != ''
-        run: sh update_version_json.sh -v ${{ inputs.version }}
-      - name: Commit and push the changes made to the version.json file
-        if: inputs.version != ''
-        run: |
-          git add version.json
-          git commit -m "update version.json"
-          git push
-      - name: Add and push new git tag
-        if: inputs.version != ''
-        run: |
-          git tag ${{ inputs.version }}
-          git push origin ${{ inputs.version }}
-      - name: ${{ (inputs.dryRun == true && 'Validate') || 'Release' }} on Cocoapods
-        env:
-          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
-        run: |
-          # make the command
-          command="${{ (inputs.dryRun == true && 'spec lint') || 'trunk push' }}"
-          # make the list of connectors
-          prefix="THEOplayer-Connector"
-          connectors=()
-          if [ "${{ inputs.connectors }}" == "All" ]; then
-            files=(*)
-            for file in ${files[*]}
-            do
-              if [[ $file == *.podspec ]]; then
-                connectors+=("$file")
-              fi
-            done
-          else
-            connectors+=("$prefix-${{ inputs.connectors }}.podspec")
-          fi
-          for connector in ${connectors[*]}
-          do
-            pod $command $connector --verbose --allow-warnings
-          done
-  Cleanup:
-    needs: Bump-And-Release
-    if: (inputs.dryRun == true && inputs.version != '') && (success() || failure())
-    runs-on: macos-latest
-    steps:
-      - name: Check out repository code
-        uses: actions/checkout@v4
-      - name: Update to latest
-        run: |
-          git fetch --all
-          git pull
-      - name: Remove and unpublish git tag
-        run: git push --delete origin refs/tags/${{ inputs.version }}
-      - name: Update(Revert) the version.json file back to the previous version
-        env:
-          PREVIOUS_VERSION: ${{ needs.Bump-And-Release.outputs.previousVersion }}
-        run: |
-          sh update_version_json.sh -v $PREVIOUS_VERSION
-      - name: Commit and push the changes made to the version.json file
-        run: |
-          git add version.json
-          git commit -m "update version.json"
-          git push
+        echo "${{ secrets.GITHUB_TOKEN }}"
+        echo "${{ github.token }}"
+      # - id: store_previous_version
+      #   run: |
+      #     previousVersion=$(ruby -r "./version.rb" -e "print_version")
+      #     echo "previousVersion=$previousVersion" >> "$GITHUB_OUTPUT"
+      # - name: Update the version.json file
+      #   if: inputs.version != ''
+      #   run: sh update_version_json.sh -v ${{ inputs.version }}
+      # - name: Commit and push the changes made to the version.json file
+      #   if: inputs.version != ''
+      #   run: |
+      #     git add version.json
+      #     git commit -m "update version.json"
+      #     git push
+      # - name: Add and push new git tag
+      #   if: inputs.version != ''
+      #   run: |
+      #     git tag ${{ inputs.version }}
+      #     git push origin ${{ inputs.version }}
+      # - name: ${{ (inputs.dryRun == true && 'Validate') || 'Release' }} on Cocoapods
+      #   env:
+      #     COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
+      #   run: |
+      #     # make the command
+      #     command="${{ (inputs.dryRun == true && 'spec lint') || 'trunk push' }}"
+      #     # make the list of connectors
+      #     prefix="THEOplayer-Connector"
+      #     connectors=()
+      #     if [ "${{ inputs.connectors }}" == "All" ]; then
+      #       files=(*)
+      #       for file in ${files[*]}
+      #       do
+      #         if [[ $file == *.podspec ]]; then
+      #           connectors+=("$file")
+      #         fi
+      #       done
+      #     else
+      #       connectors+=("$prefix-${{ inputs.connectors }}.podspec")
+      #     fi
+      #     for connector in ${connectors[*]}
+      #     do
+      #       pod $command $connector --verbose --allow-warnings
+      #     done
+  # Cleanup:
+  #   needs: Bump-And-Release
+  #   if: (inputs.dryRun == true && inputs.version != '') && (success() || failure())
+  #   runs-on: macos-latest
+  #   steps:
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v4
+  #     - name: Update to latest
+  #       run: |
+  #         git fetch --all
+  #         git pull
+  #     - name: Remove and unpublish git tag
+  #       run: git push --delete origin refs/tags/${{ inputs.version }}
+  #     - name: Update(Revert) the version.json file back to the previous version
+  #       env:
+  #         PREVIOUS_VERSION: ${{ needs.Bump-And-Release.outputs.previousVersion }}
+  #       run: |
+  #         sh update_version_json.sh -v $PREVIOUS_VERSION
+  #     - name: Commit and push the changes made to the version.json file
+  #       run: |
+  #         git add version.json
+  #         git commit -m "update version.json"
+  #         git push
